# Generated by Django 4.2.2 on 2023-06-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polygon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polygon',
            new_name='Polygone',
        ),
    ]
