# Generated by Django 4.2.2 on 2023-06-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polygon', '0002_rename_polygon_polygone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygone',
            name='name',
        ),
    ]
